ALL_TEAMS = [
    "Algeria",
    "Argentina",
    "Australia",
    "Austria",
    "Belgium",
    "Bosnia and Herzegovina",
    "Brazil",
    "Canada",
    "Cape Verde",
    "Colombia",
    "Croatia",
    "Curaçao",
    "Czech Republic",
    "DR Congo",
    "Ecuador",
    "Egypt",
    "England",
    "France",
    "Germany",
    "Ghana",
    "Haiti",
    "Iran",
    "Iraq",
    "Ivory Coast",
    "Japan",
    "Jordan",
    "Mexico",
    "Morocco",
    "Netherlands",
    "New Zealand",
    "Norway",
    "Panama",
    "Paraguay",
    "Portugal",
    "Qatar",
    "Saudi Arabia",
    "Scotland",
    "Senegal",
    "South Africa",
    "South Korea",
    "Spain",
    "Sweden",
    "Switzerland",
    "Tunisia",
    "Turkey",
    "United States",
    "Uruguay",
    "Uzbekistan",
]

WC2026_GROUPS = {
    "A": ["Mexico", "South Korea", "South Africa", "Czechia"],
    "B": ["Canada", "Switzerland", "Qatar", "Bosnia-Herzegovina"],
    "C": ["Brazil", "Morocco", "Haiti", "Scotland"],
    "D": ["United States", "Paraguay", "Australia", "Turkey"],
    "E": ["Germany", "Curacao", "Ivory Coast", "Ecuador"],
    "F": ["Netherlands", "Japan", "Sweden", "Tunisia"],
    "G": ["Belgium", "Egypt", "Iran", "New Zealand"],
    "H": ["Spain", "Cape Verde", "Saudi Arabia", "Uruguay"],
    "I": ["France", "Senegal", "Iraq", "Norway"],
    "J": ["Argentina", "Algeria", "Austria", "Jordan"],
    "K": ["Portugal", "DR Congo", "Uzbekistan", "Colombia"],
    "L": ["England", "Croatia", "Ghana", "Panama"],
}

HOST_NATIONS = ["Mexico", "Canada", "United States"]

CONFEDERATION = {
    "Mexico": "CONCACAF",
    "Canada": "CONCACAF",
    "United States": "CONCACAF",
    "Haiti": "CONCACAF",
    "Curacao": "CONCACAF",
    "Panama": "CONCACAF",
    "Brazil": "CONMEBOL",
    "Argentina": "CONMEBOL",
    "Uruguay": "CONMEBOL",
    "Colombia": "CONMEBOL",
    "Ecuador": "CONMEBOL",
    "Paraguay": "CONMEBOL",
    "Germany": "UEFA",
    "France": "UEFA",
    "Spain": "UEFA",
    "England": "UEFA",
    "Portugal": "UEFA",
    "Netherlands": "UEFA",
    "Belgium": "UEFA",
    "Croatia": "UEFA",
    "Switzerland": "UEFA",
    "Austria": "UEFA",
    "Sweden": "UEFA",
    "Norway": "UEFA",
    "Scotland": "UEFA",
    "Czechia": "UEFA",
    "Turkey": "UEFA",
    "Bosnia-Herzegovina": "UEFA",
    "South Korea": "AFC",
    "Japan": "AFC",
    "Australia": "AFC",
    "Iran": "AFC",
    "Saudi Arabia": "AFC",
    "Qatar": "AFC",
    "Uzbekistan": "AFC",
    "Jordan": "AFC",
    "Iraq": "AFC",
    "Morocco": "CAF",
    "Senegal": "CAF",
    "Egypt": "CAF",
    "Ivory Coast": "CAF",
    "Tunisia": "CAF",
    "South Africa": "CAF",
    "Ghana": "CAF",
    "DR Congo": "CAF",
    "Algeria": "CAF",
    "Cape Verde": "CAF",
    "New Zealand": "OFC",
}
